### ISSUE TITLE
Problem with LinkimputeR

### ISSUE THREAD

**Issue by vinod1981** [danielmoney/LinkImputeR#2]
Hi,
I've a very large vcf file (100 gb) with 800 individuals and 3 millions SNPs and I am using LinkimputeR to impute missing site. 
I am using the following commands through a shell script:
java -Xmx100G -jar /prj/pflaphy-robot/software/LinkImputeR.jar -s /prj/variantfilter1/accuracy_mod.ini 

But I am getting the following memory related error every time: 
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at VCF.Position.genotypeList(Position.java:106)
        at VCF.VCF.<init>(VCF.java:222)
        at Executable.Input.getVCF(Input.java:138)
        at Executable.LinkImputeR.accuracy(LinkImputeR.java:392)
        at Executable.LinkImputeR.main(LinkImputeR.java:132)

I tried various combinations of -Xmx but it is failing every time. Is it a problem of large dataset or I am missing something in my scripts.

**Comment by danielmoney** [comment]
LinkImputer does have a known issue with memory usage as it was never designed for use on very large datasets.  As it's been a while since I looked at I can't remember what the ratio between memory needed and file size is but given it holds the vcf in memory I'm pretty sure it's greater than 1 - so you'd need rather more than 100G for the Xmx value.  Even ignoring that I suspect it would struggle with that many SNPs when doing it's LD calculation.

My best advice would be to maybe split the SNPs up into multiple VCF files in some logical way, e.g. by chromosome, and then merge back together.  In theory you could lose a tiny bit of accuracy if there is a SNP  with a high correlation on another chromosome but with that many SNPs I would expect there to be enough SNPs in high LD on the same chromosome that imputation will not be effected.

If that doesn't work then you could try cutting down either further by splitting up into partially overlapping sets of SNPs and ignoring the ones at the end (since you'd expect SNPs in high correlation to be nearby).  We achieved good accuracy with much lower number of SNPs than that so, as long as the subsetting is done sensibly, I think you should be fine.

Making LinkImputeR work better with large datasets is on the longterm list of things to do but as I'm no longer employed doing anything related to LinkImputeR it could be some time before anything is implemented.

Hopefully that is of some help and sorry I couldn't give you a nice simple answer.

**Comment by vinod1981** [comment]
Hi,
Thank you very much for the elaborated reply. Even after splitting there would be around ~300000 SNPs per chromosome. Do you think this is fair number to go for imputation with LinkimputeR? 
Thanks,
Vinod

**Comment by danielmoney** [comment]
We run it, quite a few years ago now, on 660,000 SNPs with 700 individuals so I think so but make no guarantees.

One other thought that just occured to me was that seems like it could be a big file for that size dataset (although my memory could be wrong there).  Does it have a lot of extra data in it?  You could try stripping it of everything but that which LinkImputeR needs - it just needs the AD, DP and GT fields.  It also does not need anything in the INFO column (although it will need a . to be a valid vcf).

**Comment by vinod1981** [comment]
It is final file, even filtered clearly with MAF, missing sites and contains only biallelic SNPs. 
The number you showed is good, I'll try to split my vcf according to chromosome-wise and will try again.
Thanks,
Vinod,
